a=int(input('輸入係數:'))
b=int(input('輸入係數:'))
c=int(input('輸入係數:'))
d=(-b+ ((b**2)-4*a*c)**0.5) /(2*a)
e=(-b- ((b**2)-4*a*c)**0.5) /(2*a)
print('輸入係數a:',a)
print('輸入係數b:',b)
print('輸入係數c:',c)
print("方程式的根為:",'x1=',d,'x2=',e)